### ISSUE TITLE
`Accept-Language` in different casing

### ISSUE THREAD

**Issue by caridy** [jshttp/negotiator#27]
We have noticed that some browsers will send the `Accept-Language` header all in lower case (e.g.: fr-fr), some others will send it as `fr-FR`. This put a borden on the user to deal with these differences when it could be done at the lower level. Here is a repro case using npm REPL:

```
var n = require('negotiator/lib/language');
undefined
> n('en-GB', ['en-US', 'en-GB', 'fr-FR'])
[ 'en-GB' ]
> n('en-US', ['en-US', 'en-GB', 'fr-FR'])
[ 'en-US' ]
> n('en-us', ['en-US', 'en-GB', 'fr-FR'])
[]  // FAILS
> n('en-gb', ['en-US', 'en-GB', 'fr-FR'])
[]  // FAILS
```

what is the recommendation to solve this problem? can this be covered by `negotiator/lib/language` directly?

/cc @ericf

**Comment by Netail** [comment]
tbh would be nice to ignore case sensitivity
