### ISSUE TITLE
Parameter names should be case insensitive

### ISSUE THREAD

**Issue by ethanresnick** [jshttp/negotiator#37]
This comes from RFC 7231, which [says](https://tools.ietf.org/html/rfc7231#section-3.1.1.1): "The type, subtype, and parameter name tokens are case-insensitive."

Code to reproduce the issue:

```javascript
var request = {
  headers: {
    accept: 'text/html;Charset="utf-8'
  }
};

var Negotiator = require('negotiator');
var negotiator = Negotiator(request);
var availableMediaTypes = ['text/html;charset=utf-8'];

// Expected result below: 'text/html;charset=utf-8'
// Actual result: undefined
console.log(negotiator.mediaType(availableMediaTypes))
```

**Comment by dougwilson** [comment]
lol. Gosh darn it :) Eventually when the media part uses `content-type` module in the next major these issues won't happen any longer :D I appreciate the report immensely!

**Comment by ethanresnick** [comment]
Absolutely! I found this as I was digging through the RFCs to investigate #35. I'll leave a comment there soon with my findings, and open up other issues as they arise.

**Comment by dougwilson** [comment]
Alright, should be fixed now :)

**Comment by dougwilson** [comment]
Publishing to npm as 0.5.3
