### ISSUE TITLE
es6 support

### ISSUE THREAD

**Issue by cubitworx** [jshttp/negotiator#51]
I realise this is largely superficial but is there any plan to support the es6 import syntax?

**Comment by dougwilson** [comment]
Please forgive me for never using import syntax, but I can't seem to figure it out. I downloaded the latest Node.js 6.9.1 and I tried to use `import`, but keep getting `SyntaxError: Unexpected token import`. How do I use the import syntax in Node.js?

**Comment by dougwilson** [comment]
Hi @cubitworx I hope it's OK, but I'm not sure what the question is and I haven't heard back for 22 days, so going to close this issue.
