### ISSUE TITLE
[Question] parseMediaType(), and parameters after q-value

### ISSUE THREAD

**Issue by AnyhowStep** [jshttp/negotiator#57]
I was just curious about why `parseMediaType()` doesn't parse parameters after the `q` value,

https://github.com/jshttp/negotiator/blob/99f418e11907b60e63f0addc09fc596ddc7be5be/lib/mediaType.js#L75-L78

```js
//key before q
preferredMediaTypes("a/a;q=1, b/b;key=*;q=1", ["a/a","b/b"])
//b/b more preferred
//["b/b", "a/a"]

//key after q
preferredMediaTypes("a/a;q=1, b/b;q=1;key=*", ["a/a","b/b"])
//a/a more preferred
//["a/a", "b/b"]
```

**Comment by dougwilson** [comment]
Parameters are only those before the q. https://tools.ietf.org/html/rfc7231#section-5.3.2

**Comment by AnyhowStep** [comment]
Ah. All right, thank you!

**Comment by AnyhowStep** [comment]
Ah, all right. Thank you!

**Comment by AnyhowStep** [comment]
Ah, all right. Thanks!
