### ISSUE TITLE
0.6.3 Release

### ISSUE THREAD

**Issue by MumiaIrrequieta** [jshttp/negotiator#61]
Hey there,
Could you please make a release for v0.6.3? I'm trying to use the latest release of @angular/cli (13.2.0) and npm can't find this dependency.

Thanks a lot.

**Comment by dougwilson** [comment]
It was already published to npm 5 days ago. Imnot sure what else you mean by make a release.

**Comment by dougwilson** [comment]
https://www.npmjs.com/package/negotiator

> 0.6.3 • Public • Published 5 days ago

**Comment by dougwilson** [comment]
I'm sorry, I don't know what you are saying. I just pasted what it says on npm above: 0.6.3 published 5 days ago.

**Comment by MumiaIrrequieta** [comment]
![image](https://user-images.githubusercontent.com/13803119/151406329-1d62d829-2d34-4bfb-af16-90e6dd3cca5b.png)

**Comment by MumiaIrrequieta** [comment]
I see 0.6.3 on npm page, but somehow github is showing 0.6.2 as the latest version, and when I do "npm install" it doesn't find 0.6.3 :man_shrugging:

**Comment by dougwilson** [comment]
Ok, I just entered in the 0.6.3 on the github releases, sorry about that.
