### ISSUE TITLE
engines does not match ci

### ISSUE THREAD

**Issue by wraithgar** [jshttp/negotiator#72]
When [node <18 was dropped from CI](https://github.com/jshttp/negotiator/commit/8dec753f39a375750404f59ccf7439f500f516ff), the engines field was not also updated.  It still reads `>=0.6`.

I assume this is now incorrect.

```sh
$ npm view negotiator version engines
version = '1.0.0'
engines = { node: '>= 0.6' }
```

**Comment by bjohansebas** [comment]
Hi @wraithgar, you are correct, the engine has not been updated. We have an open discussion on the topic that you can see at https://github.com/expressjs/discussions/issues/286.

**Comment by wraithgar** [comment]
Closing as a duplicate then, thanks!

**Comment by blakeembrey** [comment]
@wraithgar This is a good catch and appears to be a bug/mistake when releasing 1.0.0, I'll bump that now.
